name: Déploiement Dys-Play sur Infomaniak

on:
  push:
    branches: [main]
  workflow_dispatch: # Permet le déclenchement manuel

jobs:
  deploy:
    name: Déployer sur dys-play.net
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Déploiement via rsync over SSH
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avz --delete --exclude='.git' --exclude='.github' --exclude='.gitignore' --exclude='libs/README.md' --exclude='fonts/README.md' --exclude='README.md'
          path: ./
          remote_path: ${{ secrets.INFOMANIAK_REMOTE_PATH }}
          remote_host: ${{ secrets.INFOMANIAK_HOST }}
          remote_port: ${{ secrets.INFOMANIAK_PORT }}
          remote_user: ${{ secrets.INFOMANIAK_USER }}
          remote_key: ${{ secrets.INFOMANIAK_SSH_KEY }}
