name: Déploiement Dys-Play sur Infomaniak

on:
  push:
    branches: [main]
  workflow_dispatch: # Permet le déclenchement manuel

jobs:
  deploy:
    name: Déployer sur dys-play.net
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Déploiement via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.INFOMANIAK_HOST }}
          port: 22
          protocol: sftp
          username: ${{ secrets.INFOMANIAK_USER }}
          password: ${{ secrets.INFOMANIAK_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.INFOMANIAK_REMOTE_PATH }}
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*
            **/.github*/**
            .gitignore
            README.md
            libs/README.md
            fonts/README.md
